### ISSUE TITLE
Exception when setting style to JavaScript

### ISSUE THREAD

**Issue by Haeri** [bobbylight/RSTALanguageSupport#38]
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/mozilla/javascript/ast/NodeVisitor
	at org.fife.rsta.ac.js.JavaScriptLanguageSupport.install(JavaScriptLanguageSupport.java:287)
	at org.fife.rsta.ac.LanguageSupportFactory.installSupport(LanguageSupportFactory.java:171)
	at org.fife.rsta.ac.LanguageSupportFactory.propertyChange(LanguageSupportFactory.java:190)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setSyntaxEditingStyle(RSyntaxTextArea.java:2910)
        ..
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.ast.NodeVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 48 more

Thin only occurs with my project. The DemoApp.java seems to be working fine. Not sure what the demo app is doing different, since every other language seems to work just fine.

**Comment by Haeri** [comment]
# SOLVED
I was using RSTALanguageSupport without having Gradle set up correctly. I was able to still fix the issue by having Gradle download the needed mozilla dependency and nicking it, by copy pasting the "rhino-1.7.6.jar" and adding it to my projects external dependency in the build configuration.
